; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
build_flags =
    -Os
    -flto
    -Wall
    -Wextra
    -Wno-unused-parameter

[env:megaatmega2560_min]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
build_flags =
    -Os
    -flto
    -Wall
    -Wextra
    -Wno-unused-parameter
    -DMEGATRNG_ENABLE_WATCHDOG=0
    -DMEGATRNG_ENABLE_TIMER1_PHASE=0
    -DMEGATRNG_ENABLE_WIDE_PLANES=0
